### ISSUE TITLE
Update to 6.2.1 causes infinite refresh on web

### ISSUE THREAD

**Issue by zgr024** [expo/expo-webpack-integrations#10]
### Summary

After updating to 6.2.1, running the app in web results in the following console error and an infinite refresh in the browser

`react native TypeError: (0 , _nanoid.nanoid) is not a function
`

Reverting to 6.1.0 resolves issue

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 14.21.2 - /usr/local/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 9.3.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: ~9.1.0 => 9.1.0 
      expo: ^45.0.0 => 45.0.8 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
    npmGlobalPackages:
      eas-cli: 0.47.0
      expo-cli: 6.2.1
    Expo Workflow: managed

### Please specify your device/emulator/simulator platform, model and version

Mac OS Monteray v12.6 running Brave browser; AWS Amplify

### Reproducible demo or steps to reproduce from a blank project

install expo-cli 6.2.1
run expo start -c
press w to run in web
